// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodoInput struct {
	Description string `json:"description"`
	DueDate     string `json:"dueDate"`
	FileID      string `json:"fileId"`
}

type CreateTodoPayload struct {
	Todo  *Todo       `json:"todo"`
	Error *FieldError `json:"error"`
}

type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

type Mutation struct {
}

type Query struct {
}

type SearchResult struct {
	Results []*Todo `json:"results"`
	Total   int32   `json:"total"`
	Offset  int32   `json:"offset"`
	Limit   int32   `json:"limit"`
}

type Todo struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
	DueDate     string `json:"dueDate"`
	FileID      string `json:"fileId"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}
