package handler

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"todo-service/internal/api/graphql/mapper"
	"todo-service/internal/domain/dto"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input dto.CreateTodoInput) (*dto.CreateTodoPayload, error) {

	todoItem, err := mapper.InputToEntity(input)
	if err != nil {
		return nil, err
	}

	if err := r.TodoUseCase.Create(ctx, todoItem); err != nil {
		return nil, err
	}

	return mapper.EntityToPayload(todoItem), nil
}
