package handler

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"todo-service/internal/api/graphql/mapper"
	"todo-service/internal/domain/dto"

	"github.com/99designs/gqlgen/graphql"
)

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, gfile graphql.Upload) (*dto.FileUploadResponse, error) {

	fileE, err := mapper.UploadToFileEntity(gfile)
	if err != nil {
		return nil, err
	}

	if err := r.FileUseCase.UploadFile(ctx, fileE); err != nil {
		return nil, err
	}

	return mapper.FileEntityToResponse(fileE), nil

}

// GetFile is the resolver for the getFile field.
func (r *queryResolver) GetFile(ctx context.Context, id string) (*dto.File, error) {
	panic(fmt.Errorf("not implemented: GetFile - getFile"))
}

// ListFiles is the resolver for the listFiles field.
func (r *queryResolver) ListFiles(ctx context.Context, limit *int32, offset *int32) ([]*dto.File, error) {
	panic(fmt.Errorf("not implemented: ListFiles - listFiles"))
}
