package handler

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"strconv"
	"time"
	"todo-service/internal/domain/dto"
)

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id string) (*dto.Todo, error) {
	iD, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}

	entity, err := r.TodoUseCase.GetByID(ctx, iD)
	if err != nil {
		return nil, err
	}

	s := &dto.Todo{
		ID:          int32(entity.ID),
		Description: entity.Description,
		DueDate:     entity.DueDate.Format(time.RFC3339),
		FileID:      id,
		CreatedAt:   entity.DueDate.Format(time.RFC3339),
	}

	return s, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*dto.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
