package handler

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"log"
	"todo-service/internal/api/graphql/mapper"
	"todo-service/internal/domain/dto"
)

// SearchTodos is the resolver for the searchTodos field.
func (r *queryResolver) SearchTodos(ctx context.Context, query string, offset int32, limit int32) (*dto.SearchResult, error) {
	log.Printf("SearchTodos called - query: %s, limit: %+v, offset: %+v", query, limit, offset)

	searchItem, total, err := r.TodoUseCase.Search(ctx, query, offset, limit)
	if err != nil {
		return nil, err
	}

	return mapper.EntitiesToSearchResult(searchItem, int(total), int(offset), int(limit)), nil
}
